### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by dynobo** [simonflueckiger/tesserocr-windows_build#10]
Hi,

I just tried your latest wheel on Windows 10. Installation ran through without issues, but `import tesserocr` in python fails with **`ImportError: DLL load failed. Module not found.`** 

Any ideas? Thanks!

Steps to reproduce:
```
C:\Users\dynobo>pip install https://github.com/simonflueckiger/tesserocr-windows_build/releases/download/tesserocr-v2.4.0-tesseract-4.0.0/tesserocr-2.4.0-cp37-cp37m-win_amd64.whl
Collecting tesserocr==2.4.0
  Downloading https://github.com/simonflueckiger/tesserocr-windows_build/releases/download/tesserocr-v2.4.0-tesseract-4.0.0/tesserocr-2.4.0-cp37-cp37m-win_amd64.whl (3.6MB)
     |████████████████████████████████| 3.6MB 467kB/s
Installing collected packages: tesserocr
Successfully installed tesserocr-2.4.0

C:\Users\dynobo>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tesserocr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dynobo\AppData\Local\Programs\Python\Python37\lib\site-packages\tesserocr\__init__.py", line 1, in <module>
    from ._tesserocr import *
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
>>>
```

Systeminfo:
```
C:\Users\dynobo>systeminfo
Hostname:                                      DESKTOP-K735T5H
Betriebssystemname:                            Microsoft Windows 10 Education
Betriebssystemversion:                         10.0.18362 Nicht zutreffend Build 18362
Betriebssystemhersteller:                      Microsoft Corporation
Betriebssystemkonfiguration:                   Eigenständige Arbeitsstation
Betriebssystem-Buildtyp:                       Multiprocessor Free
Registrierter Benutzer:                        Windows-Benutzer
Registrierte Organisation:
Produkt-ID:                                    00328-00085-40051-AA104
Ursprüngliches Installationsdatum:             14.09.2019, 11:18:35
Systemstartzeit:                               04.11.2019, 18:57:59
Systemhersteller:                              innotek GmbH
Systemmodell:                                  VirtualBox
Systemtyp:                                     x64-based PC
Prozessor(en):                                 1 Prozessor(en) installiert.
                                               [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1992 MHz
											   
```

**Comment by ruvindad** [comment]
You need to install Visual C++ redistributable 2013 64bit and 2015 64bit.
Or just install all the runtime from: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by dynobo** [comment]
Thanks, that worked! :-)
