### ISSUE TITLE
problem whem running main.py

### ISSUE THREAD

**Issue by xXCrowe3ye** [simonflueckiger/tesserocr-windows_build#18]
Traceback (most recent call last):
  File "C:\Users\SpikeSpiegel\Downloads\Compressed\TFT-OCR-BOT-main\main.py", line 6, in <module>
    from ui import UI
  File "C:\Users\SpikeSpiegel\Downloads\Compressed\TFT-OCR-BOT-main\ui.py", line 5, in <module>
    from win32gui import SetWindowLong, GetWindowLong, SetLayeredWindowAttributes
ModuleNotFoundError: No module named 'win32gui'

**Comment by simonflueckiger** [comment]
tesserocr does not depend on [win32gui](https://pypi.org/project/pywin32/). From the [TFT-OCR-BOT FAQ](https://github.com/jfd02/TFT-OCR-BOT?tab=readme-ov-file#faq):

> ModuleNotFoundError: No module named 'win32gui'

- Open the command prompt (cmd) and run 'pip install pywin32'.
